# netlify.toml
# This file configures Netlify deployment and redirects

[build]
  publish = "site/.vitepress/dist"
  command = "npm run docs:build"

# These redirect rules ensure proper handling of clean URLs
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
  conditions = {Role = ["anonymous"]}

# Ensure trailing slashes are handled correctly
[[plugins]]
  package = "@netlify/plugin-sitemap"

[plugins.inputs]
  buildDir = "site/.vitepress/dist"
  prettyURLs = true
  trailingSlash = false
